image: golang:1.17

stages:
  - build

build:linux64: &build-base
  stage: build
  variables:
    ARCH: linux/amd64

  before_script:
    - go install github.com/mitchellh/gox@latest
  script:
    - cd go_crawler/
    - gox -osarch="$ARCH"
  artifacts:
    paths:
      - "go_crawler/dataclassification-crawler_*"
    expire_in: 30 days

build:win64:
  <<: *build-base
  variables:
    ARCH: windows/amd64

build:macos64:
  <<: *build-base
  variables:
    ARCH: darwin/amd64