image: golang:1.17

stages:
  - build

build:
  stage: build
  script:
    - cd go_crawler/
    - go build -o $EXE_NAME
  artifacts:
    paths:
      - $EXE_NAME
    expire_in: 30 days

variables:
  EXE_NAME: "crawler"
  CONFIG_NAME: "config.toml"