stages:
  make_small_dataset:
    cmd: export PYTHONPATH=$PWD && python src/make_test_dataset.py --config=params.yaml --test_dir=data_test
    deps:
      - src/make_test_dataset.py
    outs:
      - data_test/raw
  tika_de:
    cmd: export PYTHONPATH=$PWD && python src/tika_parser.py --config=params.yaml --locale=de
    deps:
    - ${base.data_dir}/${tika.input_path}/de
    - src/tika_parser.py
    outs:
    - ${base.data_dir}/${tika.output_path}/de
    params:
      - tika
      - base

  tokenizer_de:
    cmd: "export PYTHONPATH=$PWD && \
     python -m spacy download de_core_news_sm && \
     python src/tokenizer.py --config=params.yaml --locale=de"
    deps:
      - ${base.data_dir}/${tokenizer.input_path}/de
      - src/tokenizer.py
    outs:
      - ${base.data_dir}/${tokenizer.output_path}/de
    params:
      - tokenizer
      - base

  train_de:
    cmd: "export PYTHONPATH=$PWD && \
     python src/train_model.py --config=params.yaml --locale=de"
    deps:
      - ${base.data_dir}/${train.input_path}/de
      - src/train_model.py
    outs:
      - ${train.models_path}/de/tfidf.pkl
      - ${base.data_dir}/${train.interim_path}/de/tfidf_vocab.txt
      - ${base.data_dir}/${train.interim_path}/de/tfidf_idf.txt
      - ${base.data_dir}/${train.interim_path}/de/tfidf_vocab_words.txt
      - ${train.reports_path}/de/pca_fig.pdf
      - ${train.models_path}/de/pca.pkl
      - ${base.data_dir}/${train.interim_path}/de/pca.txt
      - ${train.models_path}/de/model.txt
      # - ${train.reports_path}/metrics.json
      - ${train.reports_path}/de/confusion.pdf
    params:
      - base
      - tokenizer.industries
      - train
    metrics:
      - ${train.reports_path}/de/metrics.json:
          cache: false
    plots:
      - ${train.reports_path}/de/confusion.csv:
          title: "confusion matrix"
          template: confusion
          x: actual
          y: predicted
          cache: false