stages:
  tika_de:
    cmd: export PYTHONPATH=$PWD && python src/tika_parser.py --config=params.yaml --locale=de
    deps:
    - ${tika.input_path}/de
    - src/tika_parser.py
    outs:
    - ${tika.output_path}/de
    params:
      - tika
      - base

  tokenizer_de:
    cmd: "export PYTHONPATH=$PWD && \
     python -m spacy download de_core_news_sm && \
     python src/tokenizer.py --config=params.yaml --locale=de"
    deps:
      - ${tokenizer.input_path}/de
    outs:
      - ${tokenizer.output_path}/de
    params:
      - tokenizer
      - base

  train:
    cmd: "export PYTHONPATH=$PWD && \
     python src/train_model.py --config=params.yaml --locale=de"
    deps:
      - ${train.input_path}/de
    outs:
      - ${train.models_path}/tfidf.pickle
      - ${train.interim_path}/tfidf_vocab.txt
      - ${train.interim_path}/tfidf_idf.txt
      - ${train.interim_path}/tfidf_vocab_words.txt
      - ${train.reports_path}/pca_fig.pdf
      - ${train.models_path}/pca.pickle
      - ${train.interim_path}/pca.txt
      - ${train.models_path}/model.txt
      # - ${train.reports_path}/metrics.json
      - ${train.reports_path}/confusion.pdf
    params:
      - base
      - tokenizer.industries
      - train
    metrics:
      - ${train.reports_path}/metrics.json
      - ${train.reports_path}/confusion.csv