base:
  log_level: DEBUG
  random_seed: 42
  log_path: logs
  crawlers: [colly, google, common]
  data_dir: data_test

tika:
  # relative to `base.data_dir`
  input_path: raw/
  output_path: interim/tika/

tokenizer:
  min_tokens: 500
  max_symbols: 250000
  # relative to `base.data_dir`
  input_path: interim/tika
  output_path: interim/tokenizer
  industries: [finance_banking, it_research_development, manufacturing, medical_medicine_paramedical,
    sales_marketing_pr, businises_corporate, hr, legal, others]

train:
  # relative to `base.data_dir`
  input_path: interim/tokenizer
  interim_path: interim/train
  test_size: 0.25
  validate_size: 0.2
  max_features: 1024
  # relative to project root
  reports_path: reports/
  models_path: models/
  pca_explained_variance_threshold: 0.9
  lightgbm_parameters:
    learning_rate: [0.15]
    boosting: [gbdt]
    max_depth: [2, 4]
    objective: [multiclass]
    num_iterations: [120]
    subsample: [0.5]
    subsample_freq: [1]
    is_unbalance: [true]
    reg_lambda: [0.01]
    early_stopping_round: [3]
    metric: [multi_logloss]
    verbosity: [-1]
