boosting: gbdt
early_stopping_round: 3
is_unbalance: true
learning_rate: 0.15
max_depth: 2
metric: multi_logloss
num_class: 9
num_iterations: 240
num_leaves: 20
objective: multiclass
reg_lambda: 0.01
subsample: 0.5
subsample_freq: 1
verbosity: -1
